### ISSUE TITLE
TextFormField

### ISSUE THREAD

**Issue by pishguy** [aloklearning/flutter_bounce#3]
how can i use this library on `TextFormField` widget?

**Comment by MingSern** [comment]
@pishguy You can try using another similar package that i have developed, [flutter_bounceable](https://pub.dev/packages/flutter_bounceable). It kind of works on `TextFormField`.

**Comment by aloklearning** [comment]
Hello @pishguy, I hope @MingSern has given some insights on the problem. Since I did not receive any confirmation from your resolution status for a long time. I am assuming it is resolved. Thanks
